### PR TITLE
Comment model additions

### PR DESCRIPTION
**Pull request by kjorg50**
Adding comments (not working at the moment)

~~I need help, because I have an error that I can't figure out. I'm working on the view/controller for the path `http://localhost:3000/comments/new`, but right now there is an error that says~~

```
undefined method `comments_path' for #<#<Class:0xbb4a004>:0xbb49aa0>
```

~~I don't understand the error because I don't use the term `comments_path` anywhere in my code..... please help~~

EDIT - fixed that problem

### CODE REVIEW

**Comment by jhenkens** [comment]
@kjorg50 I mostly just fixed some routing stuff. Your create path was 'comments_create_path', not 'comments path'. You could have fixed it by using 'as' to change the name of the route helper, but just using a resource is easier.

**Comment by kjorg50** [comment]
Ah! Rails routing... 

Ok, thank you, I'll finish up the rest of comments later

**Comment by kjorg50** [comment]
ugh rebasing made the commit timeline weird...

But, now I've done what I wanted to do with comments. They are not integrated with users yet because I'm waiting for Johan's fixes to some stuff. This can be merged if we want. (since projects are not integrated with users yet either)

**Comment by jhenkens** [comment]
Holy shit did the timeline ever get messed up. That doesn't look like the rebase worked.

**Pull request merged**
